### ISSUE TITLE
The method onComplete crashes in API23

### ISSUE THREAD

**Issue by keisserdur** [traex/RippleEffect#107]
`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: info.si2.testnacionalidad, PID: 9221
                                                                         java.lang.IllegalStateException: Underflow in restore - more restores than saves
                                                                             at android.graphics.Canvas.native_restore(Native Method)
                                                                             at android.graphics.Canvas.restore(Canvas.java:540)
                                                                             at com.andexert.library.RippleView.draw(RippleView.java:166)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15174)
                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                             at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                             at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
                                                                             at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
                                                                             at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
                                                                             at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
                                                                             at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                             at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by patrickpissurno** [comment]
Please try this fixed version as alternative (you can use any targetSdkVersion): https://github.com/patrickpissurno/RippleEffect/
