### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by kumaleap** [traex/RippleEffect#108]
Process: superfish.customviewdemo, PID: 22575
                                                                          java.lang.IllegalStateException: Underflow in restore - more restores than saves
                                                                              at android.graphics.Canvas.native_restore(Native Method)
                                                                              at android.graphics.Canvas.restore(Canvas.java:540)
                                                                              at com.andexert.library.RippleView.draw(RippleView.java:166)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15198)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15158)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15158)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15158)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15158)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15158)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15158)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:15158)
                                                                              at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:282)
                                                                              at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:288)
                                                                              at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:323)
                                                                              at android.view.ViewRootImpl.draw(ViewRootImpl.java:2635)
                                                                              at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2454)
                                                                              at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2087)
                                                                              at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1127)
                                                                              at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6038)
                                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                                              at android.view.Choreographer.doFrame(Choreographer.java:608)
                                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5432)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:735)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
05-18 16:16:22.122 22575-22575/superfish.customviewdemo I/Process: Sending signal. PID: 22575 SIG: 9

**Comment by patrickpissurno** [comment]
Take a look at this fixed version: https://github.com/patrickpissurno/RippleEffect/
