### ISSUE TITLE
when run the app in android 6.0, the app crash

### ISSUE THREAD

**Issue by zhonghanwen** [traex/RippleEffect#109]
![image](https://cloud.githubusercontent.com/assets/12220537/15646691/a82c430c-2691-11e6-8694-18fd01fab618.png)

**Comment by king163** [comment]
Yes, I got the same error too in android 6.0. So I have to move this widget from my app

**Comment by zhonghanwen** [comment]
@king163 I'm going to remove this widget~

**Comment by y3k4** [comment]
Got same issue in marshmallow, @traex could you check this pull request ? https://github.com/traex/RippleEffect/pull/101 

thanx

**Comment by cocoBavan** [comment]
Same issue here.

**Comment by Alan-li** [comment]
Same issue here.

**Comment by essare** [comment]
Same error here too
at android.graphics.Canvas.restore(Canvas.java:540)
i want to remove line 166 in RippleView.java : canvas.restore(); too try what will happen but couldn't edit it because  RippleView.java is locked !!! what to do

**Comment by jgutierrez11** [comment]
+1 I have this error crash too =[

java.lang.IllegalStateException: Underflow in restore - more restores than saves
                             at android.graphics.Canvas.native_restore(Native Method)
                             at android.graphics.Canvas.restore(Canvas.java:571)

Since this is a known bug with 1 month old I will need to remove this lib from my app.

**Comment by juliusmh** [comment]
+1 gonna remove the lib

**Comment by Konraddd** [comment]
+1, any fixes? I'm getting the crash on Android 7.0 Nougat Preview

**Comment by monowar1993** [comment]
same issue faced. Need a solution

**Comment by cloudshooterhuman** [comment]
same here

**Comment by monowar1993** [comment]
@traex please have look at this issue. thanks

**Comment by hcmyleo** [comment]
crash problem  
reason：
 canvas.restore();

。。。。。

**Comment by cvisoa** [comment]
+1same issue here

**Comment by monowar1993** [comment]
is the issue is solved yet?

**Comment by pishguy** [comment]
@monowar1993 i think no, i have same problem on android 6.0.1

**Comment by ruijun** [comment]
see this commit : https://github.com/traex/RippleEffect/commit/df5f9e4456eae8a8e98e2827a3c6f9e7185596e1

The crash is be solved.

**Comment by csdaba1583** [comment]
In the crash, modified as follows：
  canvas.save();  
  canvas.restore();

**Comment by Xaus** [comment]
i've got the same issue and i removed it 
hope to solve this problem

**Comment by patrickpissurno** [comment]
Hey, I just released a fix. Check it out: https://github.com/patrickpissurno/RippleEffect/
