### ISSUE TITLE
java.lang.IllegalStateException: Underflow in restore - more restores than saves

### ISSUE THREAD

**Issue by pishguy** [traex/RippleEffect#115]
java.lang.IllegalStateException: Underflow in restore - more restores than saves
                                                                     at android.graphics.Canvas.native_restore(Native Method)
                                                                     at android.graphics.Canvas.restore(Canvas.java:540)
                                                                     at com.andexert.library.RippleView.draw(RippleView.java:166)

```
<com.andexert.library.RippleView
    android:id="@+id/market_list_as_grid_view"
    rv_centered="true"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_toRightOf="@+id/icon_list_as_two_column">
    <com.joanzapata.iconify.widget.IconTextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginLeft="8dp"
        android:gravity="center"
        android:paddingBottom="5dp"
        android:paddingLeft="5dp"
        android:paddingTop="8dp"
        android:shadowColor="#000000"
        android:text="{fa-th-large}"
        android:textColor="#ffffff"
        android:textSize="23sp"/>
</com.andexert.library.RippleView>
```

**Comment by ruijun** [comment]
@tux-world 
You can see this commit : https://github.com/traex/RippleEffect/commit/df5f9e4456eae8a8e98e2827a3c6f9e7185596e1

The crash is be solved.

**Comment by sohambannerjee8** [comment]
@ruijun .The fix is not live yet.I am also facing the same.I hope we have to wait for the next release.

**Comment by gautam2682** [comment]
same here not solved crashed on two emulators solve it so that i could use in my app otherwise effects are awesome

**Comment by abhiataero** [comment]
same issue...waiting for new release...when it will come live?????

**Comment by feng612266** [comment]
same issue...waitint for fix,android os 6.0.1

 <com.andexert.library.RippleView
           android:id="@+id/rv_my_address"
           android:layout_below="@id/rv_my_favorite"
           android:layout_width="match_parent"
           android:layout_height="wrap_content">

      <RelativeLayout
          android:id="@+id/rl_my_address"
          android:paddingLeft="@dimen/dimen_15dp"
          android:background="@drawable/selector_tab"
          android:layout_width="match_parent"
          android:layout_height="@dimen/dimen_44dp">

         <ImageView
             android:id="@+id/im_my_address"
             android:layout_width="@dimen/dimen_20dp"
             android:layout_height="@dimen/dimen_20dp"
             android:layout_centerVertical="true"
             android:src="@mipmap/icon_address" />

         <TextView
             android:id="@+id/tv_my_address"
             android:layout_width="match_parent"
             android:layout_height="wrap_content"
             android:layout_centerVertical="true"
             android:layout_marginLeft="@dimen/dimen_10dp"
             android:layout_toRightOf="@id/im_my_address"
             android:text="@string/tv_my_address"
             android:textColor="@color/text_color_63"
             android:textSize="@dimen/text_size_15" />

         <ImageView
             android:id="@+id/iv_address_arrow_right"
             android:layout_width="wrap_content"
             android:layout_height="wrap_content"
             android:layout_alignBaseline="@id/im_my_address"
             android:layout_alignParentRight="true"
             android:layout_marginRight="16dp"
             android:layout_centerVertical="true"
             android:background="@mipmap/arrow_right" />

      </RelativeLayout>

       </com.andexert.library.RippleView>

**Comment by patrickpissurno** [comment]
Hey, I just released a fix. Check it out: https://github.com/patrickpissurno/RippleEffect/

**Comment by mmchougule** [comment]
@patrickpissurno looks like your fix is working!! Thank you! :)

**Comment by CelticParser** [comment]
@patrickpissurno THNX!

**Comment by thineshvp** [comment]
@patrickpissurno, it is working. Thank you.

**Comment by alikhan-codersranch** [comment]
Thanks a lot now it's working fine. I was just about to leave this lib and finally I found the solution. Thanks buddy 👍

**Comment by afinas-em** [comment]
Thanks buddy, Really helped...

**Comment by shenbuqingyun** [comment]
Thanks！ It works！
