### ISSUE TITLE
In Marshmallow got error 

### ISSUE THREAD

**Issue by arpit999** [traex/RippleEffect#116]
See my logcat  it's says **IllegalStateException** 

`Process: com.production.home.mymichanic, PID: 3253
                                                                              java.lang.IllegalStateException: Underflow in restore - more restores than saves
                                                                                  at android.graphics.Canvas.native_restore(Native Method)
                                                                                  at android.graphics.Canvas.restore(Canvas.java:571)
                                                                                  at com.andexert.library.RippleView.draw(RippleView.java:166)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:16464)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:16424)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:16424)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:16424)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:16424)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:16424)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:16424)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:16424)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:16424)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:16424)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:16424)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:16424)
                                                                                  at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:325)
                                                                                  at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:331)
                                                                                  at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:366)
                                                                                  at android.view.ViewRootImpl.draw(ViewRootImpl.java:3134)
                                                                                  at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2933)
                                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2522)
                                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
                                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
                                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
                                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:695)
                                                                                  at android.view.Choreographer.doFrame(Choreographer.java:631)
                                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
                                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:158)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:7225)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
`

**Comment by pro-softs** [comment]
yeh i got same error too!!  installed through gradle. Really need a fix

**Comment by tschuchortdev** [comment]
I can reproduce the error. It works perfectly fine on API 16

**Comment by pro-softs** [comment]
Problem solved by adding the library manually in the project without gradle from this [link](https://codeload.github.com/traex/RippleEffect/zip/master).

**Comment by patrickpissurno** [comment]
Hey, I just released a fix. Check it out: https://github.com/patrickpissurno/RippleEffect/
