### ISSUE TITLE
ripple view crashes for targetSdkVersion above 22

### ISSUE THREAD

**Issue by HamedGh** [traex/RippleEffect#124]
please bug fix this issue!
I get this error:

`java.lang.IllegalStateException: Underflow in restore - more restores than saves
                                                               at android.graphics.Canvas.native_restore(Native Method)
                                                               at android.graphics.Canvas.restore(Canvas.java:522)
                                                               at com.andexert.library.RippleView.draw(RippleView.java:166)`

**Comment by patrickpissurno** [comment]
Hey, I just released a fix. Check it out: https://github.com/patrickpissurno/RippleEffect/

**Comment by ism33ail** [comment]
Thanks @patrickpissurno  that solves the problem 
it works for me on API 24

**Comment by literakl** [comment]
I can confirm this issue with API 24.

**Comment by Mahan3340** [comment]
have this issue on API 25
