### ISSUE TITLE
error in 7.1.1

### ISSUE THREAD

**Issue by tank777** [traex/RippleEffect#127]
Underflow in restore - more restores than save
at android.graphics.Canvas.native_restore(Native Method)

**Comment by boomsya** [comment]
the same error in Android 6

**Comment by swallowsonny** [comment]
Underflow in restore - more restores than saves

**Comment by ahmadbilalctech** [comment]
Same Issue occur on OS 6.0 

` Underflow in restore - more restores than saves
                                                                               at android.graphics.Canvas.native_restore(Native Method)
                                                                               at android.graphics.Canvas.restore(Canvas.java:540)
                                                                               at com.andexert.library.RippleView.draw(RippleView.java:166)`

**Comment by hahmadbilal** [comment]
Same issue occur on OS 6.0

` Underflow in restore - more restores than saves
                                                                               at android.graphics.Canvas.native_restore(Native Method)
                                                                               at android.graphics.Canvas.restore(Canvas.java:540)
                                                                               at com.andexert.library.RippleView.draw(RippleView.java:166)`

**Comment by boomsya** [comment]
use fork https://github.com/patrickpissurno/RippleEffect/
with fix error
tested - all OK

**Comment by afterxiong** [comment]
小米4C 7.0系统直接崩溃出现以上错误

**Comment by lazysong** [comment]
I tried the fixed version https://github.com/patrickpissurno/RippleEffect/ 
It do works! @boomsya
