### ISSUE TITLE
java.lang.IllegalStateException: Underflow in restore - more restores than saves

### ISSUE THREAD

**Issue by TengJW** [traex/RippleEffect#135]
机型：小米4c  系统版本 7.0

java.lang.IllegalStateException: Underflow in restore - more restores than saves
	at android.graphics.Canvas.native_restore(Native Method)
	at android.graphics.Canvas.restore(Canvas.java:522)
	at com.andexert.library.RippleView.draw(RippleView.java:166)
	at android.view.View.updateDisplayListIfDirty(View.java:16078)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3750)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3730)
	at android.view.View.updateDisplayListIfDirty(View.java:16041)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3750)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3730)
	at android.view.View.updateDisplayListIfDirty(View.java:16041)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3750)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3730)
	at android.view.View.updateDisplayListIfDirty(View.java:16041)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3750)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3730)
	at android.view.View.updateDisplayListIfDirty(View.java:16041)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3750)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3730)
	at android.view.View.updateDisplayListIfDirty(View.java:16041)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3750)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3730)
	at android.view.View.updateDisplayListIfDirty(View.java:16041)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:657)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:663)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:771)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2833)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2641)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2248)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1283)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6359)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
	at android.view.Choreographer.doCallbacks(Choreographer.java:685)
	at android.view.Choreographer.doFrame(Choreographer.java:621)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6342)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by uCloudCastle** [comment]
I have meet the same crash

**Comment by KomoriWu** [comment]
I have meet the same crash

**Comment by bizehao** [comment]
I have meet the same crash，in google Nexus 5x, help help help

**Comment by abolfazlbzgh** [comment]
see this commit => [df5f9e4](https://github.com/traex/RippleEffect/commit/df5f9e4456eae8a8e98e2827a3c6f9e7185596e1)

 use this code in line 166 
if (Build.VERSION.SDK_INT < 23) {
          canvas.restore();
}
