### ISSUE TITLE
trying to use a recycled bitmap android.graphics.Bitmap@4025008 on doubleRipple

### ISSUE THREAD

**Issue by chkalog** [traex/RippleEffect#30]
Hey there!

First of all before mentioning the error....Nice job there! Really simple finally something available on an version less than 12 :P
Anyway...I tried to implement the ripple:rv_type="doubleRipple" but I got this : 

12-23 17:52:35.795    5456-5456/com.jusp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.jusp, PID: 5456
    java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@4025008
            at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1225)
            at android.graphics.Canvas.drawBitmap(Canvas.java:1359)
            at com.jusp.gui.tablet.RippleView.getCircleBitmap(RippleView.java:255)
            at com.jusp.gui.tablet.RippleView.draw(RippleView.java:165)
            at android.view.View.updateDisplayListIfDirty(View.java:14048)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3388)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3367)
            at android.view.View.updateDisplayListIfDirty(View.java:14008)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3388)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3367)
            at android.view.View.updateDisplayListIfDirty(View.java:14008)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3388)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3367)
            at android.view.View.updateDisplayListIfDirty(View.java:14008)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3388)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3367)
            at android.view.View.updateDisplayListIfDirty(View.java:14008)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3388)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3367)
            at android.view.View.updateDisplayListIfDirty(View.java:14008)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:266)
            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:272)
            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:311)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2492)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2337)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1968)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

Does anyone know what would cause that?
Thanx :)

**Comment by amorenew** [comment]
holder.rowLayout.postDelayed(new Runnable() {
                @Override
                public void run() {
                    holder.rowLayout.setBackgroundColor(Color.parseColor("#E0E0E0"));
                }
            }, 250);

**Comment by ankitbatra11** [comment]
Hi,
I am also facing this issue. Could you please elaborate more on this succinct solution?
Thanks in advance.
