### ISSUE TITLE
Double Ripple not works with listview layout. Other animations works perfectly

### ISSUE THREAD

**Issue by Pomis** [traex/RippleEffect#65]
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@2d5d2d1f
            at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1282)
            at android.graphics.Canvas.drawBitmap(Canvas.java:1416)
            at com.andexert.library.RippleView.getCircleBitmap(RippleView.java:318) ...

**Comment by traex** [comment]
It works great, please take a look to my sample
